GET http://localhost/narrow-way-traffic-lights/user/get_durations.php?user_id=2
Content-Type: application/json

###

POST http://localhost/narrow-way-traffic-lights/admin/insert-duration.php
Content-Type: application/json

{
    "weekday": 4,
    "weekday-duration": 30,
    "user-id": 2
}

###

POST http://localhost/narrow-way-traffic-lights/admin/edit-duration.php
Content-Type: application/json

{
    "weekday": 4,
    "weekday-duration": 40,
    "user-id": 2
}

###

POST http://localhost/narrow-way-traffic-lights/admin/change-ip.php
Content-Type: application/json

{
    "ip_address_cam_1": "10.42.0.76",
    "ip_address_cam_2": "10.42.0.131",
    "user_id": 2
}

###

POST http://localhost/narrow-way-traffic-lights/user/get-info.php
Content-Type: application/json

{
    "user_id": 5
}

###

POST http://localhost/narrow-way-traffic-lights/includes/contact.php
Content-Type: application/json

{
    "name": "Adam",
    "email": "23-61030@g.batstate-u.edu.ph",
    "message": "Hello",
    "phone": "091234566783"
}